python Qi_main.py \
  --retriever-type e5 \
  --retriever-index-path wikipedia_e5_index/merged \
  --e5-model-path /gpfsnyu/scratch/qs2196/.cache/models/e5-large-v2 \
  --reasoner-model /gpfsnyu/scratch/qs2196/.cache/models/Qwen3-8B \
  --summarizer-model /gpfsnyu/scratch/qs2196/.cache/models/Qwen3-8B \
  --dataset hotpotqa \
  --output-dir output/search_e5 \
  --max-turns 5 \
  --max-new-tokens 2048 \
  --top-k-docs 10 \
  --max-samples 100
