cutoff_len: 2048
dataset: 1_search_training
dataset_dir: data
ddp_timeout: 180000000
do_train: true
enable_thinking: true
eval_steps: 100
eval_strategy: steps
finetuning_type: lora
flash_attn: auto
fp16: true
gradient_accumulation_steps: 4
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 10
lora_alpha: 16
lora_dropout: 0.1
lora_rank: 16
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: /gpfsnyu/scratch/qs2196/.cache/models/Qwen3-8B
num_train_epochs: 5.0
optim: adamw_torch
output_dir: saves/Qwen3-8B-Base/lora/1_search_trained_lora
packing: false
per_device_eval_batch_size: 2
per_device_train_batch_size: 2
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: sft
template: default
trust_remote_code: true
val_size: 0.1
warmup_steps: 50
