CUDA_VISIBLE_DEVICES=0 python -m flashrag.retriever.index_builder \
    --retrieval_method bge\
    --model_path /gpfsnyu/scratch/bc3088/models/bge-large-en-v1.5 \
    --corpus_path ../wiki-20231120-chunk256.jsonl \
    --save_dir ../index/ \
    --embedding_path ../index/bge-2023/emb_combined_embeddings.memmap \
    --use_fp16 \
    --max_length 512 \
    --batch_size 16 \
    --sentence_transformer \
    --faiss_type Flat \
    --save_embedding | tee ../logs/build_index.log