name: inference
exp_name: baseline 

data:
  dataset_name: hotpotqa
  dataset_split: dev
  dataset_root_dir: /scratch/yl9038/longcot-rag/data
  subset_size: null
  bon_traj_path: null # only for selecting bon trajectories

model: 
  reasoner_mode: localhost
  reasoner_name_or_path: /scratch/yl9038/models/Qwen2.5-7B-Instruct
  reasoner_url: http://127.0.0.1:30000
  summarizer_mode: localhost
  summarizer_name_or_path: /scratch/yl9038/models/QwQ-32B
  summarizer_url: http://127.0.0.1:30001
  tokenizer_path: /scratch/yl9038/models/QwQ-32B

retrieval:
  flashrag_config:
    # retrieval_method: "bge"
    # retrieval_model_path: /scratch/yl9038/models/bge-large-en-v1.5
    # index_path: /scratch/yl9038/longcot-rag/FlashRAG/index/bge_Flat.index
    # corpus_path: /scratch/yl9038/longcot-rag/FlashRAG/wiki-20231120-chunk256.jsonl
    retrieval_method: "inf-v1-1.5b"
    retrieval_model_path: /scratch/yl9038/models/inf-retriever-v1-1.5b 
    index_path: /scratch/yl9038/longcot-rag/FlashRAG/index/inf-v1-1.5b_Flat.index
    corpus_path: /scratch/yl9038/longcot-rag/FlashRAG/wiki-20181220-chunk512.jsonl
    retrieval_topk: 3
    retrieval_batch_size: 32
    retrieval_use_fp16: True
    retrieval_query_max_length: 128
    use_sentence_transformer: True
    faiss_gpu: true
    silent: false
    framework: none
    generator_model_path: /scratch/yl9038/models/Qwen2.5-7B-Instruct
    generator_max_input_len: 4096
  


train:
  batch_size: 32
  num_epochs: 10
  lr: 0.0001
  weight_decay: 0.0001
  num_workers: 4

eval:
  batch_size: 32
  num_workers: 4

inference:
  baseline: "sequential"
  prompt_templates_dir: prompts
  user_message_template_name: default_QA
  max_turns: 10
  server_params:
    log_level: error
    tp_size: 1
    dp_size: 1
    mem_fraction_static: 0.75
    schedule_conservativeness: 0.3
    schedule_policy: fcfs
  reasoner_sampling_params:
    max_new_tokens: 2048
    temperature: 0.6
    top_p: 0.95
    repetition_penalty: 1.0
    no_stop_trim: True
  summarizer_sampling_params:
    max_new_tokens: 2048
    temperature: 0.6
    top_p: 0.95
    repetition_penalty: 1.0


hydra:
  job_logging:
    root:
      level: INFO
      handlers: [console, file]
    handlers:
      console:
        class: logging.StreamHandler
        stream: ext://sys.stdout
        formatter: simple
      file:
        class: logging.FileHandler
        filename: outputs/${hydra.job.name}/${data.dataset_name}/${now:%m-%d-%H-%M-%S}.log
        formatter: simple
        mode: a
    formatters:
      simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  run:
    dir: outputs/${hydra.job.name}/${data.dataset_name}/${now:%m-%d-%H-%M-%S}_${exp_name}
