server:
  host: "0.0.0.0"
  port: 5123
  debug: false

retrieval:
  flashrag_config:
    retrieval_method: "e5"
    retrieval_model_path: /scratch/yl9038/models/e5-base-v2
    index_path: /scratch/yl9038/longcot-rag/FlashRAG/index/e5_Flat.index
    corpus_path: /scratch/yl9038/longcot-rag/FlashRAG/wiki-20181220-chunk100w.jsonl
    # retrieval_method: "inf-v1-1.5b"
    # retrieval_model_path: /scratch/yl9038/models/inf-retriever-v1-1.5b 
    # index_path: /scratch/yl9038/longcot-rag/FlashRAG/index/inf-v1-1.5b_Flat.index
    # corpus_path: /scratch/yl9038/longcot-rag/FlashRAG/wiki-20181220-chunk512.jsonl
    # retrieval_method: "bge"
    # retrieval_model_path: /scratch/yl9038/models/bge-large-en-v1.5
    # index_path: /scratch/yl9038/longcot-rag/FlashRAG/index/bge_Flat.index
    # corpus_path: /scratch/yl9038/longcot-rag/FlashRAG/wiki-20231120-chunk256.jsonl
    retrieval_topk: 10
    retrieval_batch_size: 32
    retrieval_use_fp16: True
    retrieval_query_max_length: 128
    use_sentence_transformer: True
    faiss_gpu: true
    silent: false
